### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/psi-2018#3]
- [x] Move the header box over a bit to the left & reduce the padding on the right hand side

**Comment by JacquieC** [comment]
- [ ] Found the video! After hitting play, it takes over the header - JC
- [ ] "Scroll" (in the header) is really light grey and hard to read - JC
- [ ] Navigation letters are really light and hard to read - JC

**Comment by wstecklair** [comment]
#  DESKTOP

- [ ] GDPR footer - Can we make this sticky to the bottom edge of the browser so a user can't ignore it until they acknowledge it (better than adding it to the top bar)

- [ ] Nav donate button, can we have like a slight alpha or something simple to acknowledge hover? I'd like to use the same shadow treatment like you did in the Blog/Update rotator "read more" buttons (minus the "+" transition).

- [ ] 5 Health areas on-hover doesn't show the sneak-peak info. I have it in the comp, but I think I accidentally had it turned off... sorry :/

![image](https://user-images.githubusercontent.com/28412045/40086032-826f7af0-5851-11e8-9602-a2d51aaaa85f.png)

- - - - -

- [ ] 5 Health areas modal - Can we just move the "X" up into the corner flush.

![image](https://user-images.githubusercontent.com/28412045/40086179-186e4504-5852-11e8-904d-d27413705a49.png)

- - - - -

- [ ] 4 Commitments section - Is it possible to bold the text on rollover so it has a higher contrast to the excerpt text (if it's too much of an effort then ignore this comment)...

![image](https://user-images.githubusercontent.com/28412045/40086220-5102ba26-5852-11e8-81d0-d301ba82f6ea.png)

- - - - -

- [ ] Donate pill button in footer.... C'mon, green??? hahah jk, let's treat that one the same as the one in the header section (black text with shadow on hover)

![image](https://user-images.githubusercontent.com/28412045/40086345-dda7eed8-5852-11e8-8407-eca03aca47e9.png)

- - - - -

- [ ] Footer Social icons and Donate/Careers/Resources... can we have a slight fade/alpha on hover for acknowledgement. Something simple on your end is fine :)


# MOBILE
 (iphone 8 safari)

- [ ] GDPR footer - Can we make this sticky to the bottom edge of the browser so a user can't ignore it until they acknowledge it (better than adding it to the top bar)

- - - - -

- [ ] Site is sidescrolling

![img_1136](https://user-images.githubusercontent.com/28412045/40086808-b7dc3e28-5854-11e8-8c07-306a91ba2be8.PNG)

- - - - -

- [ ] Logo/Nav missing

![img_1135](https://user-images.githubusercontent.com/28412045/40086776-92a8f380-5854-11e8-89e0-b98cf7abc013.jpg)
- - - - -

- [ ] 5 Health areas modal (same note as desktop about the X being flush). Modal looks good on mobile!

- - - - -

- [ ] Blog/Updates rotator - Can we make the active indicator dot orange instead of green?
